version: "3.8"
services:

  nginx:
    image: nginx
    ports:
      - "80:80"
  website:
    image: nginx
    ports:
      - "9527:9527"
    #networks:
    #  - overlay
    #deploy:
    #  mode: replicated
    #  replicas: 1
    #  endpoint_mode: vip
    
  mysql:
    image: mysql:8.0
    restart: alway
    environment:
       MYSQL_ROOT_PASSWORD: mysqladmin
       MYSQL_DATABASE: morty
       MYSQL_USER: root
       MYSQL_PASSWORD: mysqladmin
    #volumes:
      #- db_data:/var/lib/mysql/data
    #networks:
    #  - overlay
    #deploy:
    #  mode: replicated
    #  replicas: 2
    #  endpoint_mode: dnsrr
  redis:
    image: redis
    #volumes:
    #  - db-data:/var/lib/mysql/data
    #networks:
    #  - overlay
    #deploy:
    #  mode: replicated
    #  replicas: 2
    #  endpoint_mode: dns
  plat-admin:
    build:
      context: ./resource
      dockerfile: Dockerfile_Golang_admin_server
    image: github.com/markov/plat-admin:v1.0
    depends_on:
      - mysql
      - nginx
      - redis
    #volumes:
    #  - db-data:/var/lib/mysql/data
    #networks:
    #  - overlay
    #deploy:
    #  mode: replicated
    #  replicas: 2
    #  endpoint_mode: dnsrr
  plat-user:
    build:
      context: ./resource
      dockerfile: Dockerfile_Golang_dataplat_server
    image: github.com/markov/data-admin:v1.0
    depends_on:
      - mysql
      - nginx
      - redis
    #volumes:
      #- db-data:/var/lib/mysql/data
    #networks:
    #  - overlay
  plat-cloud:
    build:
      context: ./resource
      dockerfile: Dockerfile_Golang_cloud_server
    image: github.com/markov/cloud-admin:v1.0
    depends_on:
      - mysql
      - nginx
      - redis
    #volumes:
    #  - db-data:/var/lib/mysql/data
    #networks:
    #  - overlay
    #deploy:
    #  mode: replicated
    #  replicas: 2
    #  endpoint_mode: dns
  plat-resources:
    build:
      context: ./resource
      dockerfile: Dockerfile_Golang_sysadmin_server
    image: github.com/markov/sys-admin:v1.0
    depends_on:
      - mysql
      - nginx
      - redis
  
volumes:
  db_data: {}

#networks:
#  overlay:
